title: Kalpit Borkar
author: Kalpit Borkar
email: kalpitborkar@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Hello, I'm Kalpit Borkar. A sophomore at Indian Institute of Technology Bombay
show_excerpts: true # set to true to show excerpts on the homepage
remote_theme: samarsault/texture
# baseurl: /texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Kalpit Borkar
  tagline: Indian Institute of Technology Bombay
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false
  navigation:
    - title: Resume
      url: "/resume/Kalpit_Borkar.pdf"
    - title: Projects
      url: "/_posts/projects.md"
    

  # generate social links in footer
  social_links:
    # twitter: BorkarKalpit
    github:  kalpitborkar
    linkedIn: in/kalpitborkar
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed